### ISSUE TITLE
Demarcating source lines in html output

### ISSUE THREAD

**Issue by dbaynard** [jgm/skylighting#13]
The issue raised in jgm/pandoc#3838 :

> ![misaligned](https://user-images.githubusercontent.com/870937/29004171-3a6f6d9c-7abb-11e7-9bbb-0edea8a2a468.png)

corresponds to this library.

(from that linked issue:)

> The fundamental issue is the markdown is converted to the following html
>
> ```html
> <body>
> <div class="sourceCode"><table class="sourceCode haskell numberLines"><tr class="sourceCode"><td class="lineNumbers"><pre>1
> 2
> 3
> 4
> 5
> </pre></td>
> <td class="sourceCode"><pre><code class="sourceCode haskell">
> <span class="ot">extraLongFunctionWithVeryLongNames ::</span> a <span class="ot">-&gt;</span> a
> extraLongFunctionWithVeryLongNames <span class="fu">=</span> whenTheLineGetsTooLong <span class="fu">.</span> itWraps <span class="fu">.</span> whenPrinted <span class="fu">.</span> ifTheCSSOption <span class="st">&quot;white-space&quot;</span> <span class="fu">.</span> isSetTo <span class="st">&quot;pre-wrap&quot;</span>
> 
> <span class="ot">whenTheLineGetsTooLong ::</span> a <span class="ot">-&gt;</span> a
> whenTheLineGetsTooLong <span class="fu">=</span> id
> </code></pre></td>
> </tr></table></div>
> </body>
> ```
> 
> With `numberLines` the code is inserted into a one row, two column table, with the left column a simple list of newline-separated line numbers. 
> Without `numberLines` there is no indication what code corresponds to a line, in the html output — indeed, in the native AST line breaks are represented as `\n` but this information is lost on conversion to html.
> 
> I suspect the fix for this would be to rewrite the html writer so that `numberLines` wraps each line in a div, say (this could then be prefixed with a line number using css) or something more similar to github, where the code is presented in a table but each line has its own row.

Any solution must preserve behaviour of copy-paste: line numbers must not be copied.

---

Wrapping each line in a `div.sourceLine` is trivial; the question concerns the remaining behaviour. Options are:

1.   Add numbers using pseudo-elements (`div.sourceLine::before`) in custom css inserted into each file.
2.   Hard code the line numbers, and just add css to display them.

For the former case, a fairly minimal css required looks like:

```css
div.sourceLine {
    text-indent: -1em;
}
div.sourceLine::before {
    content: counter(line);
    counter-increment: line;
    position: relative;
    left: -1em;
    text-align: right;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    padding: 0 4px;
}

pre.sourceCode {
    margin-left: 3em;
    border-left: 1px solid #a0a0a0;
    padding-left: 4px;
}
}

code.sourceCode {
    counter-reset: line 0;
    white-space: pre-wrap;
}

.sourceCode {
    overflow: visible;
}
```

and produces

![with-line-numbers](https://user-images.githubusercontent.com/870937/29010612-628e3f42-7b24-11e7-8b24-fe84d5ac51d0.png)
